- ajax/common-ajax.php
- qc_post_doc_route_stage.php
> QC Post R/S

- ajax/kri_common-ajax.php
- ajax/kri_production_common_ajax.php
- qc_post_doc_route_stage.php
QC Post Document Route/ Stage All Process Done (07 June 2024)
> QC Post Document Route/ Stage

- ajax/common-ajax.php
- ajax/kri_common-ajax.php
- sample_collection_retest_qc.php
> retest sample 07/06/2024

- ajax/common-ajax.php
- ajax/kri_common-ajax.php
- models/qc_post_transfer_modal.php
- sample_collection_retest_qc.php
> chnges retest 08-06-2024

- models/qc_process/qc_post_doc_in_process_model.php
- models/qc_process/sample_intimation_in_process_model_kri.php
- open_transaction_for_sample_intimation_in_process.php
- qc_post_doc_route_stage.php
- sample_intimation_in_process.php
> InProcess - Production

- Classes/config.php
- ajax/common-ajax.php
- ajax/kri_common-ajax.php
- models/qc-post-doc-model.php
- models/retest_qc/qc_post_doc_retest_qc_modal.php
- open-transaction-for-qc-post-doc.php
- open_trasaction_for_qc_for_doc_retest_qc.php
> retest qc 11/06/2024

- models/retest_qc/qc_post_doc_retest_qc_modal.php
> model insument

- ajax/kri_production_common_ajax.php
- open_transaction_for_sample_collection_in_process.php
Sample Collection - POST with GRN
> Sample Collection

- ajax/common-ajax.php
- ajax/kri_production_common_ajax.php
- models/qc_process/sample_collection_route_stage_model.php
- models/qc_process/sample_intimation_route_stage_model.php
- open_trasaction_for_sample_collection_route_stage.php
- open_trasaction_for_sample_intimation_route_stage.php
- sample_collection_in_process.php
- sample_intimation_route_stage.php
> Route / Stage Testing

- open_trasaction_for_qc_for_doc_retest_qc.php
- qc_post_document_retest_qc.php
inventroy transfer  14/06/2024
> invetroy trnasfer

- ajax/kri_common-ajax.php
inventroy transfer  14/06/2024
> ajax files

- Classes/function.php
- ajax/kri_common-ajax.php
- ajax/kri_production_common_ajax.php
- models/qc_process/sample_collection_in_process_model.php
- models/retest_qc/qc_post_doc_retest_qc_modal.php
- models/retest_qc/sample_collection_retest_qc_modal.php
- models/sample-collection-model.php
- qc_post_document_retest_qc.php
- sample_collection_in_process.php
- sample_collection_retest_qc.php
> retest 15/06/24

- sample_collection_retest_qc.php
> sample collection files

- qc_post_doc_route_stage.php
> RS-Testing

- ajax/kri_production_common_ajax.php
- models/qc_process/qc_post_doc_in_process_model.php
- models/retest_qc/qc_post_doc_retest_qc_modal.php
- open_trasaction_for_qc_post_doc_in_process.php
> changes 16/06/2024

- ajax/common-ajax.php
- ajax/kri_production_common_ajax.php
- models/qc_post_document_kri_modal.php
- models/qc_process/qc_post_doc_in_process_model.php
- qc_post_doc_in_process.php
> chnges 18/06/24

- ajax/common-ajax.php
- ajax/kri_production_common_ajax.php
- models/qc_post_doc_in_process_model.php
- models/qc_process/qc_post_doc_in_process_model.php
- models/qc_process/sample_collection_in_process_model.php
- qc_post_doc_in_process.php
- sample_collection_in_process.php
> changes 20-04-2024

- ajax/kri_common-ajax.php
- ajax/kri_production_common_ajax.php
- models/qc_process/sample_collection_finished_goods_model.php
- sample-collection.php
- sample_collection_in_finished_goods.php
- sample_collection_in_process.php
> Changes 24/06/24

- Classes/function.php
- ajax/kri_production_common_ajax.php
- models/qc_process/sample_intimation_finished_goods_model.php
- models/qc_process/sample_intimation_in_process_model_kri.php
- open_transaction_for_sample_intimation_in_process.php
- open_trasaction_for_qc_for_doc_retest_qc.php
- sample_intimation_finished_goods.php
- sample_intimation_in_process.php
Production In-Process Sample Intimation Testing Point resolve
> InProcess - Testing

- ajax/kri_production_common_ajax.php
- open_transaction_for_sample_intimation_in_process.php
- sample_intimation_in_process.php
Production- FG-Sample Intimation Testing Point Done
> Production- FG-Sample Intimation

- ajax/common-ajax.php
- ajax/kri_production_common_ajax.php
- models/qc_process/qc_check_finished_goods_model.php
- models/qc_process/sample_collection_finished_goods_model.php
- models/qc_process/sample_collection_in_process_model.php
- open_trasaction_for_qc_check_finished_goods.php
- sample_collection_in_finished_goods.php
- sample_collection_in_process.php
- sample_collection_retest_qc.php
> chnages 25/06/24

- models/qc_process/qc_check_finished_goods_model.php
- open_trasaction_for_qc_check_finished_goods.php
- open_trasaction_for_qc_post_doc_in_process.php
> changes 26/06/24

- Classes/function.php
- ajax/kri_production_common_ajax.php
- models/qc_process/qc_check_finished_goods_model.php
- qc_check_finished_goods.php
- qc_post_doc_in_process.php
> chnges 2-07-2024

- models/qc_process/qc_check_finished_goods_model.php
- qc_check_finished_goods.php
> chnges  2/07/24

- ajax/kri_common-ajax.php
- ajax/kri_production_common_ajax.php
- models/qc_process/qc_check_finished_goods_model.php
- qc_check_finished_goods.php
> Last changes in  qc post fg

- ajax/common-ajax.php
- models/qc_process/qc_check_finished_goods_model.php
- open_trasaction_for_qc_check_finished_goods.php
- stability-plan.php
> FG Finally Done

- ajax/kri_production_common_ajax.php
- models/qc_process/qc_post_doc_in_process_model.php
- open_trasaction_for_qc_post_doc_in_process.php
- qc_check_finished_goods.php
- qc_post_doc_in_process.php
In Process all testing point raised by Bhavik - Resolved Done
> In Process

- models/qc_process/stability-qc-check-model.php
> Changes Stability qc

- ajax/kri_production_common_ajax.php
- models/qc_process/stability-qc-check-model.php
- open_trasaction_for_qc_post_doc_stability.php
- qc_check_finished_goods.php
- qc_post_doc_in_process.php
> changes Saturday Sunday

- ajax/kri_production_common_ajax.php
- models/qc_process/stability-qc-check-model.php
- qc_post_doc_stability.php
> additional files

- ajax/common-ajax.php
- ajax/kri_production_common_ajax.php
- models/qc_process/sample_intimation_in_process_model.php
- open_transaction_for_sample_intimation_stability.php
- qc_check_finished_goods.php
- qc_post_doc_stability.php
- sample_intimation_in_process.php
- stability-plan.php
> Issue Point

- ajax/common-ajax.php
- ajax/kri_production_common_ajax.php
- include/header.php
- models/retest_qc/sample_intimation_retest_qc_modal.php
- open_transaction_for_sample_intimation_stability.php
- open_trasaction_for_sample_collection_stability.php
- open_trasaction_for_sample_intimation_retest_qc.php
- sample_collection_in_process.php
- sample_collection_stability.php
- stability-plan.php
> Production QC - Stability Issue Point

- ajax/common-ajax.php
- ajax/kri_common-ajax.php
- ajax/kri_production_common_ajax.php
- models/qc_process/qc_post_doc_in_process_model.php
- models/qc_process/sample_collection_in_process_model.php
- models/qc_process/sample_intimation_in_process_model.php
- models/retest_qc/qc_post_doc_retest_qc_modal.php
- models/retest_qc/sample_collection_retest_qc_modal.php
- models/retest_qc/sample_intimation_retest_qc_modal.php
- open_trasaction_for_qc_post_doc_in_process.php
- open_trasaction_for_sample_collection_retest_qc.php
- open_trasaction_for_sample_intimation_retest_qc.php
- qc_post_document_retest_qc.php
- sample_collection_retest_qc.php
- sample_intimation_in_process.php
- sample_intimation_retest_qc.php
Retest QC & InProcess QC Issue Point Resolve
> Retest QC & InProcess QC Issue Point Resolve

- ajax/common-ajax.php
- ajax/kri_common-ajax.php
- ajax/kri_production_common_ajax.php
- models/qc_process/qc_check_finished_goods_model.php
- models/qc_process/sample_collection_in_process_model.php
- open_transaction_for_sample_intimation_finished_goods.php
- open_trasaction_for_qc_post_doc_in_process.php
- open_trasaction_for_qc_post_doc_stability.php
- qc_check_finished_goods.php
- sample_collection_in_process.php
- sample_collection_retest_qc.php
- sample_intimation_finished_goods.php
- sample_intimation_retest_qc.php
Baroque Pharma All Testing Point Done
> Baroque Pharma All Testing Point Done

- ajax/common-ajax.php
- models/qc_process/sample_collection_finished_goods_model.php
- open_trasaction_for_sample_collection_stability.php
- qc_post_doc_stability.php
- sample_collection_in_finished_goods.php
- sample_intimation_stability.php
> Stability QC Iuuse Resolve

- ajax/common-ajax.php
- ajax/kri_common-ajax.php
- ajax/kri_production_common_ajax.php
- open-sample-collection.php
- open_transaction_for_sample_collection_in_process.php
- open_transaction_for_sample_intimation_stability.php
- open_trasaction_for_qc_for_doc_retest_qc.php
- open_trasaction_for_qc_post_doc_stability.php
- qc_post_doc_stability.php
- stability-plan.php
> All Transaction Point Closed

- ajax/common-ajax.php
- ajax/kri_production_common_ajax.php
Open QC and POST Doc QC row level validation compliance and non compliance closed
> Open QC and POST Doc QC row level validation compliance and non compliance closed

- Classes/function.php
- ajax/kri_production_common_ajax.php
- include/header.php
- open-transaction-for-qc-post-doc.php
- open_transaction_for_qc_post_doc_route_stage.php
- open_trasaction_for_qc_post_doc_in_process.php
code enhancement and add ItemCode and Batch Filter in POST Doc QC
> code enhancement and add ItemCode and Batch Filter in POST Doc QC
